FROM node:14 as deps

WORKDIR /app

COPY package*.json .

RUN npm install

FROM node:14 as start

WORKDIR /app

COPY --from=deps /app/node_modules /node_modules

COPY . .

EXPOSE 8000

CMD ["node", "server.js"]